package com.boot.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Casebatch extends CasebatchKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.BatchNo
     *
     * @mbggenerated
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CustomerNo
     *
     * @mbggenerated
     */
    private String customerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CaseDate
     *
     * @mbggenerated
     */
    private Date caseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CaseType
     *
     * @mbggenerated
     */
    private String caseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.AgingType
     *
     * @mbggenerated
     */
    private String agingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CaseTemplateNo
     *
     * @mbggenerated
     */
    private String caseTemplateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CaseTotalNumber
     *
     * @mbggenerated
     */
    private Integer caseTotalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CaseTotalAmount
     *
     * @mbggenerated
     */
    private BigDecimal caseTotalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.ImportStatus
     *
     * @mbggenerated
     */
    private String importStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.FilterStatus
     *
     * @mbggenerated
     */
    private String filterStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.Valid
     *
     * @mbggenerated
     */
    private String valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CreaterNo
     *
     * @mbggenerated
     */
    private String createrNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CreatedDate
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.ModifierNo
     *
     * @mbggenerated
     */
    private String modifierNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CaseNumber
     *
     * @mbggenerated
     */
    private Integer caseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.AllocationCnt
     *
     * @mbggenerated
     */
    private Integer allocationCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.NoAllocationCnt
     *
     * @mbggenerated
     */
    private Integer noAllocationCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.ErrorLogPath
     *
     * @mbggenerated
     */
    private String errorLogPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.CorpNo
     *
     * @mbggenerated
     */
    private String corpNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.GroupNo
     *
     * @mbggenerated
     */
    private String groupNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.DeptNo
     *
     * @mbggenerated
     */
    private String deptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.OperatorNo
     *
     * @mbggenerated
     */
    private String operatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.GridFsId
     *
     * @mbggenerated
     */
    private String gridFsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table casebatch
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.BatchNo
     *
     * @return the value of casebatch.BatchNo
     * @mbggenerated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.BatchNo
     *
     * @param batchNo the value for casebatch.BatchNo
     * @mbggenerated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CustomerNo
     *
     * @return the value of casebatch.CustomerNo
     * @mbggenerated
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CustomerNo
     *
     * @param customerNo the value for casebatch.CustomerNo
     * @mbggenerated
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CaseDate
     *
     * @return the value of casebatch.CaseDate
     * @mbggenerated
     */
    public Date getCaseDate() {
        return caseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CaseDate
     *
     * @param caseDate the value for casebatch.CaseDate
     * @mbggenerated
     */
    public void setCaseDate(Date caseDate) {
        this.caseDate = caseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CaseType
     *
     * @return the value of casebatch.CaseType
     * @mbggenerated
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CaseType
     *
     * @param caseType the value for casebatch.CaseType
     * @mbggenerated
     */
    public void setCaseType(String caseType) {
        this.caseType = caseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.AgingType
     *
     * @return the value of casebatch.AgingType
     * @mbggenerated
     */
    public String getAgingType() {
        return agingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.AgingType
     *
     * @param agingType the value for casebatch.AgingType
     * @mbggenerated
     */
    public void setAgingType(String agingType) {
        this.agingType = agingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CaseTemplateNo
     *
     * @return the value of casebatch.CaseTemplateNo
     * @mbggenerated
     */
    public String getCaseTemplateNo() {
        return caseTemplateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CaseTemplateNo
     *
     * @param caseTemplateNo the value for casebatch.CaseTemplateNo
     * @mbggenerated
     */
    public void setCaseTemplateNo(String caseTemplateNo) {
        this.caseTemplateNo = caseTemplateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CaseTotalNumber
     *
     * @return the value of casebatch.CaseTotalNumber
     * @mbggenerated
     */
    public Integer getCaseTotalNumber() {
        return caseTotalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CaseTotalNumber
     *
     * @param caseTotalNumber the value for casebatch.CaseTotalNumber
     * @mbggenerated
     */
    public void setCaseTotalNumber(Integer caseTotalNumber) {
        this.caseTotalNumber = caseTotalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CaseTotalAmount
     *
     * @return the value of casebatch.CaseTotalAmount
     * @mbggenerated
     */
    public BigDecimal getCaseTotalAmount() {
        return caseTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CaseTotalAmount
     *
     * @param caseTotalAmount the value for casebatch.CaseTotalAmount
     * @mbggenerated
     */
    public void setCaseTotalAmount(BigDecimal caseTotalAmount) {
        this.caseTotalAmount = caseTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.ImportStatus
     *
     * @return the value of casebatch.ImportStatus
     * @mbggenerated
     */
    public String getImportStatus() {
        return importStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.ImportStatus
     *
     * @param importStatus the value for casebatch.ImportStatus
     * @mbggenerated
     */
    public void setImportStatus(String importStatus) {
        this.importStatus = importStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.FilterStatus
     *
     * @return the value of casebatch.FilterStatus
     * @mbggenerated
     */
    public String getFilterStatus() {
        return filterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.FilterStatus
     *
     * @param filterStatus the value for casebatch.FilterStatus
     * @mbggenerated
     */
    public void setFilterStatus(String filterStatus) {
        this.filterStatus = filterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.Remark
     *
     * @return the value of casebatch.Remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.Remark
     *
     * @param remark the value for casebatch.Remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.Valid
     *
     * @return the value of casebatch.Valid
     * @mbggenerated
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.Valid
     *
     * @param valid the value for casebatch.Valid
     * @mbggenerated
     */
    public void setValid(String valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CreaterNo
     *
     * @return the value of casebatch.CreaterNo
     * @mbggenerated
     */
    public String getCreaterNo() {
        return createrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CreaterNo
     *
     * @param createrNo the value for casebatch.CreaterNo
     * @mbggenerated
     */
    public void setCreaterNo(String createrNo) {
        this.createrNo = createrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CreatedDate
     *
     * @return the value of casebatch.CreatedDate
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CreatedDate
     *
     * @param createdDate the value for casebatch.CreatedDate
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.ModifierNo
     *
     * @return the value of casebatch.ModifierNo
     * @mbggenerated
     */
    public String getModifierNo() {
        return modifierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.ModifierNo
     *
     * @param modifierNo the value for casebatch.ModifierNo
     * @mbggenerated
     */
    public void setModifierNo(String modifierNo) {
        this.modifierNo = modifierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CaseNumber
     *
     * @return the value of casebatch.CaseNumber
     * @mbggenerated
     */
    public Integer getCaseNumber() {
        return caseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CaseNumber
     *
     * @param caseNumber the value for casebatch.CaseNumber
     * @mbggenerated
     */
    public void setCaseNumber(Integer caseNumber) {
        this.caseNumber = caseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.AllocationCnt
     *
     * @return the value of casebatch.AllocationCnt
     * @mbggenerated
     */
    public Integer getAllocationCnt() {
        return allocationCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.AllocationCnt
     *
     * @param allocationCnt the value for casebatch.AllocationCnt
     * @mbggenerated
     */
    public void setAllocationCnt(Integer allocationCnt) {
        this.allocationCnt = allocationCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.NoAllocationCnt
     *
     * @return the value of casebatch.NoAllocationCnt
     * @mbggenerated
     */
    public Integer getNoAllocationCnt() {
        return noAllocationCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.NoAllocationCnt
     *
     * @param noAllocationCnt the value for casebatch.NoAllocationCnt
     * @mbggenerated
     */
    public void setNoAllocationCnt(Integer noAllocationCnt) {
        this.noAllocationCnt = noAllocationCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.ErrorLogPath
     *
     * @return the value of casebatch.ErrorLogPath
     * @mbggenerated
     */
    public String getErrorLogPath() {
        return errorLogPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.ErrorLogPath
     *
     * @param errorLogPath the value for casebatch.ErrorLogPath
     * @mbggenerated
     */
    public void setErrorLogPath(String errorLogPath) {
        this.errorLogPath = errorLogPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.CorpNo
     *
     * @return the value of casebatch.CorpNo
     * @mbggenerated
     */
    public String getCorpNo() {
        return corpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.CorpNo
     *
     * @param corpNo the value for casebatch.CorpNo
     * @mbggenerated
     */
    public void setCorpNo(String corpNo) {
        this.corpNo = corpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.GroupNo
     *
     * @return the value of casebatch.GroupNo
     * @mbggenerated
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.GroupNo
     *
     * @param groupNo the value for casebatch.GroupNo
     * @mbggenerated
     */
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.DeptNo
     *
     * @return the value of casebatch.DeptNo
     * @mbggenerated
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.DeptNo
     *
     * @param deptNo the value for casebatch.DeptNo
     * @mbggenerated
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.OperatorNo
     *
     * @return the value of casebatch.OperatorNo
     * @mbggenerated
     */
    public String getOperatorNo() {
        return operatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.OperatorNo
     *
     * @param operatorNo the value for casebatch.OperatorNo
     * @mbggenerated
     */
    public void setOperatorNo(String operatorNo) {
        this.operatorNo = operatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.GridFsId
     *
     * @return the value of casebatch.GridFsId
     * @mbggenerated
     */
    public String getGridFsId() {
        return gridFsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.GridFsId
     *
     * @param gridFsId the value for casebatch.GridFsId
     * @mbggenerated
     */
    public void setGridFsId(String gridFsId) {
        this.gridFsId = gridFsId;
    }
}