package com.boot.entity;

import java.io.Serializable;
import java.util.Date;

public class CasebatchKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casebatch.ModifiedDate
     *
     * @mbggenerated
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table casebatch
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.id
     *
     * @return the value of casebatch.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.id
     *
     * @param id the value for casebatch.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casebatch.ModifiedDate
     *
     * @return the value of casebatch.ModifiedDate
     * @mbggenerated
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casebatch.ModifiedDate
     *
     * @param modifiedDate the value for casebatch.ModifiedDate
     * @mbggenerated
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}